name: Check Authorization for schema changes

on:
  pull_request:
    branches:
    - main

jobs:
  check_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Commit Author
        id: get_author
        run: |
          echo "commit_author=$(git log -1 --pretty=format:'%ae')" >> $GITHUB_ENV
      
      - name: Get GitHub Team Members
        id: get_team_members
        run: |
          curl -H "Authorization: token ${{ secrets.TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/orgs/superlinked/teams/vdb-table-maintainers/members \
            > team.json
        env:
          TOKEN: ${{ secrets.SUPERLINKED_PAT_TOKEN }}

      - name: Check if vendor.schema.json has changed
        id: check_file_change
        run: |
          # Path of the specific file to check
          file_path="docs/tools/vdb_table/vendor.schema.json"
          
          # Check if the file has changed
          if git diff --name-only HEAD~1 | grep -q "$file_path"; then
            echo "File $file_path has changed."
          else
            echo "File $file_path has not changed."
            exit 0
          fi

      - name: Check if Commit Author is a Team Member
        id: check_author
        run: |
          commit_author="${{ env.commit_author }}"
          if jq -e ".[] | select(.email == \"$commit_author\")" team.json > /dev/null; then
            echo "Authorized change."
          else
            echo "Unauthorized change detected!"
            exit 1
          fi
